[package]
name = "conway"
version = "0.1.0"
authors = ["Christopher Lane <lanechr@gmail.com>"]

[dependencies]
image = "0.15.0"
piston = "0.32.0"
piston-gfx_texture = "0.26.0"
piston-texture = "0.5.0"
piston_window = "0.69.0"
rand = "0.3"